
name: ePyscope_training       # name of dataset
folder: data                  # folder to put the data in
input:                        # links to files
#    bam: ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/NA12878/NIST_NA12878_HG001_HiSeq_300x/RMNISTHS_30xdownsample.bam
    bam: https://github.com/PROSIC/libprosic/blob/master/tests/test.bam?raw=true
#    bai: ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/NA12878/NIST_NA12878_HG001_HiSeq_300x/RMNISTHS_30xdownsample.bam.bai
    bai: https://github.com/PROSIC/libprosic/blob/master/tests/test.bam.bai?raw=true
profile: myProfile
